name = "devc"
main = "src/index.ts"
compatibility_date = "2023-03-06"
kv_namespaces = [
    { binding = "devc", id = "f91b259be2274a5f8eb9eceef6ee1476" }
]

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "devc"
database_id = "efaee172-7614-48c4-a59a-bcb747edcb48"